name: Git - Sync with Upstream

on:
  schedule:
    - cron: "30 0 * * 0"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up upstream
        run: |
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
